### ISSUE TITLE
Uncaught exception on startup

### ISSUE THREAD

**Issue by mwittig** [atus/pimatic-bme280#2]
The following seems to be related to an exception thrown by the underlying library:

![image](https://user-images.githubusercontent.com/6117742/30478859-13c0b710-9a13-11e7-9ff7-b39baa9de7c1.png)

The issue had been originally posted by @zmathe91 at https://github.com/pimatic/pimatic/issues/1080

**Comment by datenfalke** [comment]
I am getting the same error with a BME280 sensor connected through I2C.

It looks like the sensor is online on the I2C:

pi@raspberrypi:~ $ i2cdetect -y 1                                                                                 
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f                                                               
00:          -- -- -- -- -- -- -- -- -- -- -- -- --                                                               
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- 76 -- 

pi@raspberrypi:~ $ i2cdump -y 1 0x76 
No size specified (using byte-data access)
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: XX XX XX 00 00 00 00 00 00 00 00 00 00 00 00 00    XXX.............
10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
80: 98 6f 89 48 b1 06 31 06 a0 6c 28 67 32 00 e7 92    ?o?H??1??l(g2.??
90: 0a d6 d0 0b 21 29 12 ff f9 ff ac 26 0a d8 bd 10    ????!)?.?.?&????
a0: 00 4b 95 00 00 00 00 00 00 00 00 00 33 00 00 c0    .K?.........3..?
b0: 00 54 00 00 00 00 60 02 00 01 ff ff 1f 60 03 00    .T....`?.?..?`?.
c0: 00 00 00 ff 00 00 00 00 00 00 00 00 00 00 00 00    ................
d0: 60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    `...............
e0: 00 65 01 00 14 2a 03 1e ba 41 ff ff ff ff ff ff    .e?.?*???A......
f0: ff 00 00 00 00 00 00 80 00 00 80 00 00 80 00 80    .......?..?..?.?



pi@raspberrypi:~/pimatic-app $ sudo node_modules/pimatic/pimatic.js 
00:02:19.972 2017-11-19 Sunday
00:02:29.418 [pimatic] Starting pimatic version 0.9.42
00:02:33.246 [pimatic, ppm] 2.15.12
00:02:33.328 [pimatic] Loading plugin: "pimatic-cron" (0.8.8)
00:02:34.169 [pimatic] Loading plugin: "pimatic-mobile-frontend" (0.9.12)
00:02:35.617 [pimatic] Loading plugin: "pimatic-homeduino" (0.9.11)
00:02:36.765 [pimatic] Loading plugin: "pimatic-bme280" (0.1.2)
00:02:36.809 [pimatic-cron] the time is: Sun Nov 19 2017 00:02:36 GMT+0100 (CET)
00:02:37.783 [pimatic] New device "Luft1"...
00:02:37.895 [pimatic] New device "Wasser1"...
00:02:38.022 [pimatic-homeduino] data: "ready"
00:02:38.041 [pimatic-homeduino] Connected to homeduino device.
00:02:38.487 [pimatic-mobile-frontend] packing static assets
00:02:39.103 [pimatic-mobile-frontend] packing static assets finished
00:02:39.119 [pimatic-mobile-frontend] rendering html
00:02:41.590 [pimatic-homeduino] data: "ACK"
00:02:53.161 [pimatic-mobile-frontend] rendering html finished
00:02:53.213 [pimatic-homeduino] Receiving on pin 0
00:02:53.242 [pimatic] Listening for HTTP-request on port 80...
00:03:37.501 [pimatic] New device "y"...
00:03:37.720 [pimatic] An uncaught exception occurred: TypeError: Cannot read property 'dig_T1' of undefined
00:03:37.720 [pimatic]>    at Function.BME280.compensateTemperature (/home/pi/pimatic-app/node_modules/pimatic-bme280/node_modules/node-bme280/BME280.js:156:35)
00:03:37.720 [pimatic]>    at /home/pi/pimatic-app/node_modules/pimatic-bme280/node_modules/node-bme280/BME280.js:144:29
00:03:37.720 [pimatic]>    at Immediate._onImmediate (/home/pi/pimatic-app/node_modules/pimatic-bme280/node_modules/node-bme280/node_modules/i2c/lib/i2c.coffee:85:9)
00:03:37.720 [pimatic]>    at processImmediate [as _immediateCallback] (timers.js:383:17)
00:03:37.720 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
00:03:37.730 [pimatic] shutting pimatic down...
/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:98
          return framework.destroy().then(function() {
                 ^

ReferenceError: framework is not defined
    at process.uncaughtException (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:85:9)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at processEmit [as emit] (/home/pi/pimatic-app/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:146:32)
    at process._fatalException (node.js:224:26)

**Comment by datenfalke** [comment]
I had this problem with a not correct working GND cable between sensor and raspberrypi.

**Comment by mwittig** [comment]
OK, nevertheless, the plugin should handle exception and report errors accordingly

**Comment by atus** [comment]
Agreed, I'll look around for guidance on handling errors.
